travis:
  secure:
    BINSTAR_TOKEN: S6PUBqMn8WPavbF2zj1Q2+xsUKce/j74rCnummKSf2FmBAIcTYsnMPfNY7hbxQjKr5nRvhOCfkc6gxFvK3OuA2RKTs7+ACQPxjUw3QkvcuQsMfpivLjaljee4Aa7MaW6KBu0z1MadJyBZhT6y1dqhdeQ8PACEgY53HYJkker4RbV9/GSEQVuWAs5HqzzjsaZJZa0VmxsE2+gagc856mmfa3S8NxVJl1sdAZmhPp9Lykf/DI+1ruKjAZfB3U4/61MyrKFnaj1B55EzGkKcqx441AleSHc5bfhNadBiHUkNOSusEvi2uGdGO1wnOFcC+PmVzGx3+d72RH5e8UCKyfJ3U89DEEet7+cIoiCz299vxuDBP/1coNivSlEuNonvYkaa/uTmA2L+KYY3vF2swyX+bbqgRVyuV00pbLxhzRvMc5OkBsc249+ha+EhDLGUR/SM8eFpzKqU0KHZT6OAVvg82aLHCAhyfdWfpoydGHkUOchSQgMNO+5PfA4nORYj3zDkcnITvJ9dD7udZfEuUFIHtHgKDv6R9Oazxpg5qZ4p84l7uWAL7WGLJGyYSvSXB8pCQz+PJvKPmUviBOpMsoqvtRrZMkRIJV/Z28/GeYlKWoF/P3YhTzSvrUv6mzfrCJ1NWXiNRi2FVKlEZ34ItmTBtbNS+/q3EuvxJklHdsJ640=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
